name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Install XCB and GL dependencies
        run: |
          sudo apt update
          # baseview dependencies
          sudo apt install libx11-xcb-dev libxcb-dri2-0-dev libgl1-mesa-dev libxcb-icccm4-dev libxcursor-dev libxcb-{render,shape,xfixes}0-dev
        if: contains(matrix.os, 'ubuntu')
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy --verbose -- -D warnings
      - name: Audit
        # RUSTSEC-2020-0097: xcb - Soundness issue with base::Error
        # RUSTSEC-2021-0019: xcb - Multiple soundness issues
        # RUSTSEC-2021-0119: nix - Out-of-bounds write in nix::unistd::getgrouplist - waiting for new winit release
        # RUSTSEC-2020-0159: chrono - Dev Dependency
        # RUSTSEC-2020-0071: time - Dev Dependency
        # RUSTSEC-2022-0048: xml-rs is Unmaintained
        # RUSTSEC-2022-0056: clipboard is Unmaintained
        run: cargo audit --deny warnings --ignore RUSTSEC-2020-0097 --ignore RUSTSEC-2021-0019 --ignore RUSTSEC-2021-0119 --ignore RUSTSEC-2020-0159 --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2022-0048 --ignore RUSTSEC-2022-0056